version: '3.7'

services:
  traefik:
    container_name: traefik
    image: traefik:2.4.8
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
      - target: 8080
        published: 8080
        mode: host
    command:
      - --api.insecure=true
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --providers.file.filename=traefik_dynamic_conf.yml
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --accesslog
      - --log
    volumes:
      - ./certs:/certs
      - ./docker-traefik-dev-conf.yml:/traefik_dynamic_conf.yml
      - /var/run/docker.sock:/var/run/docker.sock:ro
